[config]
# models
model = "gpt-6-astra"
fallback_models = ["gpt-5.6-sol"]
custom_model_max_tokens = 272000

[github_action_config]
auto_review = true
auto_describe = true
auto_improve = false
handle_push_trigger = true

[pr_code_suggestions]
commitable_code_suggestions = true
num_code_suggestions_per_chunk = 4
